/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Hall = IDL.Variant({
  'terra' : IDL.Null,
  'tileFactory' : IDL.Null,
  'businessHall' : IDL.Null,
  'others' : IDL.Null,
  'frenchHall' : IDL.Null,
});
export const TimeOfDay = IDL.Variant({
  'day' : IDL.Null,
  'evening' : IDL.Null,
});
export const BookingInput = IDL.Record({
  'customerName' : IDL.Text,
  'functionDate' : Timestamp,
  'settlementAmount' : IDL.Nat,
  'advanceReceived' : IDL.Nat,
  'hall' : Hall,
  'rentAmount' : IDL.Nat,
  'bookingDate' : Timestamp,
  'discount' : IDL.Nat,
  'totalCashReceipt' : IDL.Nat,
  'totalBankReceipt' : IDL.Nat,
  'timeOfDay' : TimeOfDay,
  'remarks' : IDL.Text,
});
export const BookingId = IDL.Nat;
export const Booking = IDL.Record({
  'id' : BookingId,
  'customerName' : IDL.Text,
  'functionDate' : Timestamp,
  'settlementAmount' : IDL.Nat,
  'advanceReceived' : IDL.Nat,
  'hall' : Hall,
  'createdAt' : Timestamp,
  'rentAmount' : IDL.Nat,
  'updatedAt' : Timestamp,
  'bookingDate' : Timestamp,
  'discount' : IDL.Nat,
  'totalCashReceipt' : IDL.Nat,
  'totalBankReceipt' : IDL.Nat,
  'timeOfDay' : TimeOfDay,
  'remarks' : IDL.Text,
  'balanceReceivable' : IDL.Int,
});
export const DashboardStats = IDL.Record({
  'totalPendingAmount' : IDL.Int,
  'pendingBookingsCount' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalCashReceipt' : IDL.Nat,
  'totalBankReceipt' : IDL.Nat,
});
export const MonthlySummary = IDL.Record({
  'totalPendingAmount' : IDL.Int,
  'month' : IDL.Nat,
  'totalRentAmount' : IDL.Nat,
  'totalAdvanceReceived' : IDL.Nat,
  'year' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalSettlementAmount' : IDL.Nat,
  'totalCashReceipt' : IDL.Nat,
  'totalBankReceipt' : IDL.Nat,
  'totalDiscount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func([BookingInput], [Booking], []),
  'deleteBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getBookingsByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getBookingsByDateRange' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMonthlySummary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlySummary],
      ['query'],
    ),
  'getPendingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'updateAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateBooking' : IDL.Func([BookingId, BookingInput], [IDL.Bool], []),
  'verifyAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Hall = IDL.Variant({
    'terra' : IDL.Null,
    'tileFactory' : IDL.Null,
    'businessHall' : IDL.Null,
    'others' : IDL.Null,
    'frenchHall' : IDL.Null,
  });
  const TimeOfDay = IDL.Variant({ 'day' : IDL.Null, 'evening' : IDL.Null });
  const BookingInput = IDL.Record({
    'customerName' : IDL.Text,
    'functionDate' : Timestamp,
    'settlementAmount' : IDL.Nat,
    'advanceReceived' : IDL.Nat,
    'hall' : Hall,
    'rentAmount' : IDL.Nat,
    'bookingDate' : Timestamp,
    'discount' : IDL.Nat,
    'totalCashReceipt' : IDL.Nat,
    'totalBankReceipt' : IDL.Nat,
    'timeOfDay' : TimeOfDay,
    'remarks' : IDL.Text,
  });
  const BookingId = IDL.Nat;
  const Booking = IDL.Record({
    'id' : BookingId,
    'customerName' : IDL.Text,
    'functionDate' : Timestamp,
    'settlementAmount' : IDL.Nat,
    'advanceReceived' : IDL.Nat,
    'hall' : Hall,
    'createdAt' : Timestamp,
    'rentAmount' : IDL.Nat,
    'updatedAt' : Timestamp,
    'bookingDate' : Timestamp,
    'discount' : IDL.Nat,
    'totalCashReceipt' : IDL.Nat,
    'totalBankReceipt' : IDL.Nat,
    'timeOfDay' : TimeOfDay,
    'remarks' : IDL.Text,
    'balanceReceivable' : IDL.Int,
  });
  const DashboardStats = IDL.Record({
    'totalPendingAmount' : IDL.Int,
    'pendingBookingsCount' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalCashReceipt' : IDL.Nat,
    'totalBankReceipt' : IDL.Nat,
  });
  const MonthlySummary = IDL.Record({
    'totalPendingAmount' : IDL.Int,
    'month' : IDL.Nat,
    'totalRentAmount' : IDL.Nat,
    'totalAdvanceReceived' : IDL.Nat,
    'year' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalSettlementAmount' : IDL.Nat,
    'totalCashReceipt' : IDL.Nat,
    'totalBankReceipt' : IDL.Nat,
    'totalDiscount' : IDL.Nat,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func([BookingInput], [Booking], []),
    'deleteBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getBookingsByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByDateRange' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMonthlySummary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlySummary],
        ['query'],
      ),
    'getPendingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'updateAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateBooking' : IDL.Func([BookingId, BookingInput], [IDL.Bool], []),
    'verifyAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };