/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'customerName' : string,
  'functionDate' : Timestamp,
  'settlementAmount' : bigint,
  'advanceReceived' : bigint,
  'hall' : Hall,
  'createdAt' : Timestamp,
  'rentAmount' : bigint,
  'updatedAt' : Timestamp,
  'bookingDate' : Timestamp,
  'discount' : bigint,
  'totalCashReceipt' : bigint,
  'totalBankReceipt' : bigint,
  'timeOfDay' : TimeOfDay,
  'remarks' : string,
  'balanceReceivable' : bigint,
}
export type BookingId = bigint;
export interface BookingInput {
  'customerName' : string,
  'functionDate' : Timestamp,
  'settlementAmount' : bigint,
  'advanceReceived' : bigint,
  'hall' : Hall,
  'rentAmount' : bigint,
  'bookingDate' : Timestamp,
  'discount' : bigint,
  'totalCashReceipt' : bigint,
  'totalBankReceipt' : bigint,
  'timeOfDay' : TimeOfDay,
  'remarks' : string,
}
export interface DashboardStats {
  'totalPendingAmount' : bigint,
  'pendingBookingsCount' : bigint,
  'totalBookings' : bigint,
  'totalCashReceipt' : bigint,
  'totalBankReceipt' : bigint,
}
export type Hall = { 'terra' : null } |
  { 'tileFactory' : null } |
  { 'businessHall' : null } |
  { 'others' : null } |
  { 'frenchHall' : null };
export interface MonthlySummary {
  'totalPendingAmount' : bigint,
  'month' : bigint,
  'totalRentAmount' : bigint,
  'totalAdvanceReceived' : bigint,
  'year' : bigint,
  'totalBookings' : bigint,
  'totalSettlementAmount' : bigint,
  'totalCashReceipt' : bigint,
  'totalBankReceipt' : bigint,
  'totalDiscount' : bigint,
}
export type TimeOfDay = { 'day' : null } |
  { 'evening' : null };
export type Timestamp = bigint;
export interface _SERVICE {
  'createBooking' : ActorMethod<[BookingInput], Booking>,
  'deleteBooking' : ActorMethod<[BookingId], boolean>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[BookingId], [] | [Booking]>,
  'getBookingsByCustomer' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByDateRange' : ActorMethod<
    [Timestamp, Timestamp],
    Array<Booking>
  >,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMonthlySummary' : ActorMethod<[bigint, bigint], MonthlySummary>,
  'getPendingBookings' : ActorMethod<[], Array<Booking>>,
  'updateAdminCredentials' : ActorMethod<[string, string, string], boolean>,
  'updateBooking' : ActorMethod<[BookingId, BookingInput], boolean>,
  'verifyAdmin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];