/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = bigint;
export type Timestamp = bigint;
export interface BookingInput {
    customerName: string;
    functionDate: Timestamp;
    settlementAmount: bigint;
    advanceReceived: bigint;
    hall: Hall;
    rentAmount: bigint;
    bookingDate: Timestamp;
    discount: bigint;
    totalCashReceipt: bigint;
    totalBankReceipt: bigint;
    timeOfDay: TimeOfDay;
    remarks: string;
}
export interface Booking {
    id: BookingId;
    customerName: string;
    functionDate: Timestamp;
    settlementAmount: bigint;
    advanceReceived: bigint;
    hall: Hall;
    createdAt: Timestamp;
    rentAmount: bigint;
    updatedAt: Timestamp;
    bookingDate: Timestamp;
    discount: bigint;
    totalCashReceipt: bigint;
    totalBankReceipt: bigint;
    timeOfDay: TimeOfDay;
    remarks: string;
    balanceReceivable: bigint;
}
export interface MonthlySummary {
    totalPendingAmount: bigint;
    month: bigint;
    totalRentAmount: bigint;
    totalAdvanceReceived: bigint;
    year: bigint;
    totalBookings: bigint;
    totalSettlementAmount: bigint;
    totalCashReceipt: bigint;
    totalBankReceipt: bigint;
    totalDiscount: bigint;
}
export interface DashboardStats {
    totalPendingAmount: bigint;
    pendingBookingsCount: bigint;
    totalBookings: bigint;
    totalCashReceipt: bigint;
    totalBankReceipt: bigint;
}
export enum Hall {
    terra = "terra",
    tileFactory = "tileFactory",
    businessHall = "businessHall",
    others = "others",
    frenchHall = "frenchHall"
}
export enum TimeOfDay {
    day = "day",
    evening = "evening"
}
export interface backendInterface {
    createBooking(input: BookingInput): Promise<Booking>;
    deleteBooking(id: BookingId): Promise<boolean>;
    getAllBookings(): Promise<Array<Booking>>;
    getBooking(id: BookingId): Promise<Booking | null>;
    getBookingsByCustomer(name: string): Promise<Array<Booking>>;
    getBookingsByDateRange(startDate: Timestamp, endDate: Timestamp): Promise<Array<Booking>>;
    getDashboardStats(): Promise<DashboardStats>;
    getMonthlySummary(year: bigint, month: bigint): Promise<MonthlySummary>;
    getPendingBookings(): Promise<Array<Booking>>;
    updateAdminCredentials(currentPassword: string, newUsername: string, newPassword: string): Promise<boolean>;
    updateBooking(id: BookingId, input: BookingInput): Promise<boolean>;
    verifyAdmin(username: string, password: string): Promise<boolean>;
}
import type { Booking as _Booking, BookingId as _BookingId, BookingInput as _BookingInput, Hall as _Hall, TimeOfDay as _TimeOfDay, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBooking(arg0: BookingInput): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Booking_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Booking_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBooking(arg0: BookingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: BookingId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByCustomer(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByCustomer(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByCustomer(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByDateRange(arg0: Timestamp, arg1: Timestamp): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDateRange(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDateRange(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMonthlySummary(arg0: bigint, arg1: bigint): Promise<MonthlySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0, arg1);
            return result;
        }
    }
    async getPendingBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAdminCredentials(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async updateBooking(arg0: BookingId, arg1: BookingInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, to_candid_BookingInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, to_candid_BookingInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyAdmin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdmin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Booking_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Hall_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Hall): Hall {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TimeOfDay_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeOfDay): TimeOfDay {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    customerName: string;
    functionDate: _Timestamp;
    settlementAmount: bigint;
    advanceReceived: bigint;
    hall: _Hall;
    createdAt: _Timestamp;
    rentAmount: bigint;
    updatedAt: _Timestamp;
    bookingDate: _Timestamp;
    discount: bigint;
    totalCashReceipt: bigint;
    totalBankReceipt: bigint;
    timeOfDay: _TimeOfDay;
    remarks: string;
    balanceReceivable: bigint;
}): {
    id: BookingId;
    customerName: string;
    functionDate: Timestamp;
    settlementAmount: bigint;
    advanceReceived: bigint;
    hall: Hall;
    createdAt: Timestamp;
    rentAmount: bigint;
    updatedAt: Timestamp;
    bookingDate: Timestamp;
    discount: bigint;
    totalCashReceipt: bigint;
    totalBankReceipt: bigint;
    timeOfDay: TimeOfDay;
    remarks: string;
    balanceReceivable: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        functionDate: value.functionDate,
        settlementAmount: value.settlementAmount,
        advanceReceived: value.advanceReceived,
        hall: from_candid_Hall_n9(_uploadFile, _downloadFile, value.hall),
        createdAt: value.createdAt,
        rentAmount: value.rentAmount,
        updatedAt: value.updatedAt,
        bookingDate: value.bookingDate,
        discount: value.discount,
        totalCashReceipt: value.totalCashReceipt,
        totalBankReceipt: value.totalBankReceipt,
        timeOfDay: from_candid_TimeOfDay_n11(_uploadFile, _downloadFile, value.timeOfDay),
        remarks: value.remarks,
        balanceReceivable: value.balanceReceivable
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    terra: null;
} | {
    tileFactory: null;
} | {
    businessHall: null;
} | {
    others: null;
} | {
    frenchHall: null;
}): Hall {
    return "terra" in value ? Hall.terra : "tileFactory" in value ? Hall.tileFactory : "businessHall" in value ? Hall.businessHall : "others" in value ? Hall.others : "frenchHall" in value ? Hall.frenchHall : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: null;
} | {
    evening: null;
}): TimeOfDay {
    return "day" in value ? TimeOfDay.day : "evening" in value ? TimeOfDay.evening : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BookingInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingInput): _BookingInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Hall_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Hall): _Hall {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TimeOfDay_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeOfDay): _TimeOfDay {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    functionDate: Timestamp;
    settlementAmount: bigint;
    advanceReceived: bigint;
    hall: Hall;
    rentAmount: bigint;
    bookingDate: Timestamp;
    discount: bigint;
    totalCashReceipt: bigint;
    totalBankReceipt: bigint;
    timeOfDay: TimeOfDay;
    remarks: string;
}): {
    customerName: string;
    functionDate: _Timestamp;
    settlementAmount: bigint;
    advanceReceived: bigint;
    hall: _Hall;
    rentAmount: bigint;
    bookingDate: _Timestamp;
    discount: bigint;
    totalCashReceipt: bigint;
    totalBankReceipt: bigint;
    timeOfDay: _TimeOfDay;
    remarks: string;
} {
    return {
        customerName: value.customerName,
        functionDate: value.functionDate,
        settlementAmount: value.settlementAmount,
        advanceReceived: value.advanceReceived,
        hall: to_candid_Hall_n3(_uploadFile, _downloadFile, value.hall),
        rentAmount: value.rentAmount,
        bookingDate: value.bookingDate,
        discount: value.discount,
        totalCashReceipt: value.totalCashReceipt,
        totalBankReceipt: value.totalBankReceipt,
        timeOfDay: to_candid_TimeOfDay_n5(_uploadFile, _downloadFile, value.timeOfDay),
        remarks: value.remarks
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Hall): {
    terra: null;
} | {
    tileFactory: null;
} | {
    businessHall: null;
} | {
    others: null;
} | {
    frenchHall: null;
} {
    return value == Hall.terra ? {
        terra: null
    } : value == Hall.tileFactory ? {
        tileFactory: null
    } : value == Hall.businessHall ? {
        businessHall: null
    } : value == Hall.others ? {
        others: null
    } : value == Hall.frenchHall ? {
        frenchHall: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeOfDay): {
    day: null;
} | {
    evening: null;
} {
    return value == TimeOfDay.day ? {
        day: null
    } : value == TimeOfDay.evening ? {
        evening: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
